version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install typescript yarn -g
      - yarn install
  build:
    commands:
      - echo Build Starting...
      - yarn run build
  post_build:
    commands:
      - echo Build Finished.

artifacts:
  files:
    - 'dist/**/*'
  discard-paths: no
