---
name: Trigger Blue Green Deployment

on:
  push:
    branches:
      - code-pipelinep

jobs:
  update-launch-template:
    runs-on: ubuntu-latest

    steps:
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Trigger Blue/Green Deployment - Blue (Currently running) | Green (New Application Revision)
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.CODE_DEPLOY_APP_NAME }} \
            --deployment-group-name ${{ secrets.CODE_DEPLOY_DEPLOYMENT_GROUP }} \
            --s3-location bucket=${{ secrets.S3_BUCKET }},bundleType=zip,key=${{ secrets.S3_OBJECT_KEY }},
